"""``CredentialStore`` — the credential-persistence port for the CLI auth subsystem.

A core-owned driven port: the inbound CLI auth commands depend on this contract,
and outbound adapters implement it (the keychain-backed
``adapters.outbound.cli_auth.credentials.KeyringCredentialStore`` in production; an
in-memory fake in tests). The concrete is built at the composition root
(``bootstrap.cli_auth_wiring.build_credential_store``), so no inbound code
constructs an adapter directly.

The contract is pure (``Path``/``str``/``dict`` only) — no transport or
infrastructure types leak through it.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class CredentialStore(Protocol):
    """Credential persistence surface used by the auth flows and command impls."""

    # --- paths / Potpie account ------------------------------------------
    def credentials_path(self) -> Path: ...

    def get_stored_api_key(self) -> str: ...

    def get_stored_api_base_url(self) -> str: ...

    def write_api_base_url(self, api_base_url: Optional[str]) -> None: ...

    def store_potpie_api_key(self, api_key: str, *, created_at: str) -> None: ...

    def store_potpie_firebase_refresh_token(
        self,
        refresh_token: str,
        *,
        created_at: str,
        firebase_api_key: str | None = None,
    ) -> None: ...

    def store_potpie_firebase_id_token(self, id_token: str) -> None: ...

    def update_potpie_firebase_refresh_token(self, refresh_token: str) -> None: ...

    def get_potpie_auth_type(self) -> str: ...

    def get_potpie_firebase_refresh_token(self) -> str: ...

    def get_potpie_firebase_id_token(self) -> str: ...

    def get_potpie_firebase_api_key(self) -> str: ...

    def clear_potpie_auth(self, *, clear_api_key: bool = False) -> None: ...

    # --- generic provider credentials (github) ---------------------------
    def get_provider_credentials(self, provider: str) -> dict[str, Any]: ...

    def write_provider_credentials(self, provider: str, payload: dict[str, Any]) -> None: ...

    def clear_provider_credentials(self, provider: str) -> None: ...

    # --- integrations (linear / atlassian) -------------------------------
    def get_integration_tokens(self, provider: str) -> dict[str, Any]: ...

    def save_integration_tokens(self, provider: str, tokens: dict[str, Any]) -> None: ...

    def clear_integration_tokens(self, provider: str) -> None: ...

    def get_integration_status(self, provider: str) -> dict[str, Any]: ...

    def list_integration_providers(self) -> list[str]: ...

    # --- Atlassian product credentials + workspace prefs -----------------
    def get_jira_credentials(self) -> dict[str, Any]: ...

    def save_jira_credentials(self, credentials: dict[str, Any]) -> None: ...

    def clear_jira_credentials(self) -> None: ...

    def get_confluence_credentials(self) -> dict[str, Any]: ...

    def save_confluence_credentials(self, credentials: dict[str, Any]) -> None: ...

    def clear_confluence_credentials(self) -> None: ...

    def get_atlassian_credentials(self) -> dict[str, Any]: ...

    def save_atlassian_credentials(self, credentials: dict[str, Any]) -> None: ...

    def clear_atlassian_credentials(self) -> None: ...

    def save_jira_workspace_prefs(self, *, project_key: str) -> None: ...

    def save_confluence_workspace_prefs(self, *, space_key: str) -> None: ...


__all__ = ["CredentialStore"]
