#!/usr/bin/env python3
"""Generate an agent-surface Markdown reference from the canonical surface.

The hand-written contract now lives in
``docs/context-graph/architecture.md#agent-contract``. This script reads the
*single* source of truth for the agent surface - ``potpie_context_core.agent_context_port``
(the same intent recipes, default includes, and ontology-derived include tiers
the runtime serves) - and emits a deterministic Markdown reference table.

Usage::

    python -m scripts.generate_agent_contract > docs/context-graph/agent-surface.generated.md
"""

from __future__ import annotations

import sys
from typing import TextIO

from potpie_context_core.agent_context_port import (
    CONTEXT_RESOLVE_RECIPES,
    context_port_manifest,
)
from potpie_context_core.context_records import (
    PREFERENCE_AUDIENCES,
    PREFERENCE_STRENGTHS,
    SCOPE_KINDS,
    VERIFICATION_OUTCOMES,
)


def emit(stream: TextIO) -> None:
    print("# Agent Surface (generated)\n", file=stream)
    print(
        "_This file is generated by `scripts/generate_agent_contract.py` from "
        "`potpie_context_core.agent_context_port`. Compare it with "
        "`docs/context-graph/architecture.md#agent-contract`._\n",
        file=stream,
    )

    print("## Intents\n", file=stream)
    print("| Intent | When | Default Includes |", file=stream)
    print("|---|---|---|", file=stream)
    for intent in sorted(CONTEXT_RESOLVE_RECIPES):
        recipe = CONTEXT_RESOLVE_RECIPES[intent]
        when = recipe.get("when", "")
        includes = ", ".join(recipe.get("include", ()))
        print(f"| `{intent}` | {when} | {includes} |", file=stream)
    print(file=stream)

    print("## Includes\n", file=stream)
    print(
        "Include keys are grouped by how the engine can answer them today "
        "(honest capability map, derived from the ontology + resolver routing):\n",
        file=stream,
    )
    families = context_port_manifest()["include_families"]
    for tier, label in (
        ("reader_backed", "Reader-backed (answered by a P9 use-case reader)"),
        ("planned", "Planned (requestable but not yet backed - best-effort only)"),
    ):
        keys = families.get(tier, [])
        print(f"### {label}\n", file=stream)
        print(", ".join(f"`{k}`" for k in keys) if keys else "_(none)_", file=stream)
        print(file=stream)

    print("## Record-type vocabularies\n", file=stream)
    print(
        "These enumerations validate the structured `context_record` payload "
        "(rebuild plan P6).\n",
        file=stream,
    )
    print("### Scope kinds\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(SCOPE_KINDS)), file=stream)
    print(file=stream)
    print("### Preference strengths\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(PREFERENCE_STRENGTHS)), file=stream)
    print(file=stream)
    print("### Preference audiences\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(PREFERENCE_AUDIENCES)), file=stream)
    print(file=stream)
    print("### Verification outcomes\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(VERIFICATION_OUTCOMES)), file=stream)
    print(file=stream)


def main() -> int:
    emit(sys.stdout)
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
