"""New migration

Revision ID: 20241026151704_e824fba2b86a
Revises: 20241003153813_827623103002
Create Date: 2024-10-26 15:17:04.343173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20241026151704_e824fba2b86a'
down_revision: Union[str, None] = '20241003153813_827623103002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_public')
    # ### end Alembic commands ###
