"""Add agent id support in conversation table

Revision ID: 20240828094302_48240c0ce09e
Revises: 20240826215938_3c7be0985b17
Create Date: 2024-08-28 09:43:02.922148

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20240828094302_48240c0ce09e"
down_revision: Union[str, None] = "20240826215938_3c7be0985b17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('agent_ids', sa.ARRAY(sa.String()), nullable=False))
    # op.alter_column('messages', 'status',
    #            existing_type=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', name='message_status_enum'),
    #            type_=sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='messagestatus'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'ACTIVE'::message_status_enum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'status',
               existing_type=sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='messagestatus'),
               type_=postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', name='message_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::message_status_enum"))
    op.drop_column('conversations', 'agent_ids')
    # ### end Alembic commands ###
