"""Add agents table and relationships

Revision ID: 20240814204937_0cac59a32122
Revises: 20240813145447_56e7763c7d20
Create Date: 2024-08-14 20:49:37.840460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20240814204937_0cac59a32122'
down_revision: Union[str, None] = '20240813145447_56e7763c7d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.Enum('LANGCHAIN', 'CUSTOM', 'CREWAI', name='providertype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DEPRECATED', name='agentstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversation_agents',
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE')
    )
    op.drop_column('conversations', 'agent_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('agent_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_table('conversation_agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
