"""Support for usage

Revision ID: 20241201204918_43646f647287
Revises: 20241127095409_625f792419e7
Create Date: 2024-12-01 20:49:18.051567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20241201204918_43646f647287'
down_revision: Union[str, None] = '20241127095409_625f792419e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('usage_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('messages_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage')
    # ### end Alembic commands ###
