"""Remove unique_text_version_user constraint
Revision ID: 20250621130556_bcbe001128d1
Revises: 20250310201406_97a740b07a50
Create Date: 2025-06-21 13:05:56.361347
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20250621130556_bcbe001128d1"
down_revision: Union[str, None] = "20250310201406_97a740b07a50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_text_version_user", "prompts", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_text_version_user", "prompts", ["text", "version", "created_by"]
    )
    # ### end Alembic commands ###
