"""add_dspy_agents_table

Revision ID: 20251216161851_ea7ba63790f7
Revises: 20250928_simple_global_cache
Create Date: 2025-12-16 16:18:51.203304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20251216161851_ea7ba63790f7'
down_revision: Union[str, None] = '20250928_simple_global_cache'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dspy_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('dspy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_inference_cache_content_hash'), table_name='inference_cache')
    op.drop_index(op.f('ix_inference_cache_created_at'), table_name='inference_cache')
    op.drop_index(op.f('ix_inference_cache_id'), table_name='inference_cache')
    op.drop_index(op.f('ix_inference_cache_last_accessed'), table_name='inference_cache')
    op.drop_index(op.f('ix_inference_cache_project_id'), table_name='inference_cache')
    op.drop_table('inference_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('node_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inference_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding_vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_accessed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('inference_cache_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inference_cache_pkey'))
    )
    op.create_index(op.f('ix_inference_cache_project_id'), 'inference_cache', ['project_id'], unique=False)
    op.create_index(op.f('ix_inference_cache_last_accessed'), 'inference_cache', ['last_accessed'], unique=False)
    op.create_index(op.f('ix_inference_cache_id'), 'inference_cache', ['id'], unique=False)
    op.create_index(op.f('ix_inference_cache_created_at'), 'inference_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_cache_content_hash'), 'inference_cache', ['content_hash'], unique=True)
    op.drop_table('dspy_agents')
    # ### end Alembic commands ###
