"""Bootstrap a local self-hosted Hatchet against the existing potpie_postgres.

Creates the ``hatchet`` database idempotently, boots the Hatchet compose services
(``hatchet`` profile), mints an API token via ``hatchet-admin``, and writes
``.env.hatchet.local`` (gitignored). Re-running is safe: token creation is skipped
when a token is already present.

Shell boundaries go through an injectable ``run`` callable so the logic is unit
testable without Docker/Postgres/Hatchet. Invoked by scripts/setup_hatchet_local.sh.
"""

from __future__ import annotations

import logging
import subprocess
import time
from pathlib import Path
from typing import Callable, Sequence

logger = logging.getLogger(__name__)

DEFAULT_CONTAINER = "potpie_postgres"
DEFAULT_DB_USER = "postgres"
DEFAULT_DB_NAME = "hatchet"
DEFAULT_TENANT_ID = "707d0855-80ab-4e1f-a156-f1c4546cbf52"
DEFAULT_HOST_PORT = "localhost:7077"
DEFAULT_SERVER_URL = "http://localhost:8080"
DEFAULT_TLS_STRATEGY = "none"
ENV_FILE = ".env.hatchet.local"

Runner = Callable[[Sequence[str]], "subprocess.CompletedProcess"]


def _run(cmd: Sequence[str]) -> "subprocess.CompletedProcess":
    """Default boundary: run a command, capturing output, without raising."""
    return subprocess.run(list(cmd), capture_output=True, text=True)


def token_present_in_env(env_path: str = ENV_FILE) -> bool:
    """True when ``env_path`` exists and HATCHET_CLIENT_TOKEN has a non-empty value."""
    path = Path(env_path)
    if not path.exists():
        return False
    for line in path.read_text().splitlines():
        line = line.strip()
        if line.startswith("HATCHET_CLIENT_TOKEN="):
            return bool(line.split("=", 1)[1].strip())
    return False


def write_env_file(
    env_path: str,
    token: str,
    *,
    host_port: str = DEFAULT_HOST_PORT,
    server_url: str = DEFAULT_SERVER_URL,
    tls_strategy: str = DEFAULT_TLS_STRATEGY,
) -> None:
    """Write the gitignored Hatchet client env file consumed by the worker/API."""
    content = (
        "# Auto-generated by scripts/setup_hatchet_local.sh — gitignored, do not commit.\n"
        f"HATCHET_CLIENT_TOKEN={token}\n"
        f"HATCHET_CLIENT_HOST_PORT={host_port}\n"
        f"HATCHET_CLIENT_SERVER_URL={server_url}\n"
        f"HATCHET_CLIENT_TLS_STRATEGY={tls_strategy}\n"
    )
    Path(env_path).write_text(content)


def ensure_hatchet_database(
    run: Runner = _run,
    *,
    container: str = DEFAULT_CONTAINER,
    user: str = DEFAULT_DB_USER,
    db_name: str = DEFAULT_DB_NAME,
) -> bool:
    """Create the ``hatchet`` database if absent. Returns True if it was created."""
    select_sql = f"SELECT 1 FROM pg_database WHERE datname='{db_name}'"
    result = run(["docker", "exec", container, "psql", "-U", user, "-tAc", select_sql])
    if getattr(result, "returncode", 0) != 0:
        raise RuntimeError(
            f"Failed to query database list (rc={result.returncode}): "
            f"{getattr(result, 'stderr', '')}"
        )
    if (result.stdout or "").strip() == "1":
        logger.info("Database %r already exists", db_name)
        return False
    create_result = run(
        [
            "docker",
            "exec",
            container,
            "psql",
            "-U",
            user,
            "-c",
            f"CREATE DATABASE {db_name}",
        ]
    )
    if getattr(create_result, "returncode", 0) != 0:
        raise RuntimeError(
            f"Failed to create database {db_name!r} (rc={create_result.returncode}): "
            f"{getattr(create_result, 'stderr', '')}"
        )
    logger.info("Created database %r", db_name)
    return True


def create_api_token(run: Runner = _run, *, tenant_id: str = DEFAULT_TENANT_ID) -> str:
    """Mint a Hatchet API token via the setup-config service; return the token string."""
    result = run(
        [
            "docker",
            "compose",
            "run",
            "--no-deps",
            "hatchet-setup-config",
            "/hatchet/hatchet-admin",
            "token",
            "create",
            "--config",
            "/hatchet/config",
            "--tenant-id",
            tenant_id,
        ]
    )
    if getattr(result, "returncode", 0) != 0:
        raise RuntimeError(
            f"hatchet token create failed (rc={result.returncode}): {getattr(result, 'stderr', '')}"
        )
    lines = [ln.strip() for ln in (result.stdout or "").splitlines() if ln.strip()]
    if not lines:
        raise RuntimeError("hatchet token create produced no output")
    return lines[-1]


def _wait_for_postgres(
    run: Runner = _run,
    *,
    container: str = DEFAULT_CONTAINER,
    user: str = DEFAULT_DB_USER,
    retries: int = 30,
    delay: float = 1.0,
) -> None:
    for _ in range(retries):
        result = run(["docker", "exec", container, "pg_isready", "-U", user])
        if getattr(result, "returncode", 0) == 0:
            return
        time.sleep(delay)
    raise RuntimeError(
        f"Postgres container {container!r} not ready after {retries} attempts"
    )


def bootstrap(
    run: Runner = _run,
    env_path: str = ENV_FILE,
    *,
    do_compose: bool = True,
    tenant_id: str = DEFAULT_TENANT_ID,
) -> None:
    """Idempotently set up local Hatchet and write ``.env.hatchet.local``."""
    if do_compose:
        postgres_up = run(["docker", "compose", "up", "-d", "postgres"])
        if getattr(postgres_up, "returncode", 0) != 0:
            raise RuntimeError(
                f"Failed to start postgres (rc={postgres_up.returncode}): "
                f"{getattr(postgres_up, 'stderr', '')}"
            )
        _wait_for_postgres(run)
    ensure_hatchet_database(run=run)
    if do_compose:
        hatchet_up = run(
            [
                "docker",
                "compose",
                "--profile",
                "hatchet",
                "up",
                "-d",
                "hatchet-engine",
                "hatchet-dashboard",
            ]
        )
        if getattr(hatchet_up, "returncode", 0) != 0:
            raise RuntimeError(
                f"Failed to start hatchet services (rc={hatchet_up.returncode}): "
                f"{getattr(hatchet_up, 'stderr', '')}"
            )
    if token_present_in_env(env_path):
        logger.info("%s already has a token — skipping token creation", env_path)
        return
    token = create_api_token(run=run, tenant_id=tenant_id)
    write_env_file(env_path, token)
    logger.info("Wrote %s", env_path)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    bootstrap()


if __name__ == "__main__":
    main()
