#!/usr/bin/env python3
"""Generate ``agent-contract.md`` from the canonical envelope catalog (P8).

Per the plan's P8 exit criterion: "agent-contract.md is generated; CI
fails on drift." This script reads the canonical intent + include enums
from ``domain.agent_envelope`` and emits a Markdown table describing
them. Running it produces deterministic output, so CI can diff against
the committed copy.

Usage::

    python -m scripts.generate_agent_contract > docs/agent-contract.generated.md
"""

from __future__ import annotations

import sys
from typing import TextIO

from domain.agent_envelope import (
    AgentInclude,
    AgentIntent,
    INTENT_INCLUDES,
)
from domain.context_records import (
    PREFERENCE_AUDIENCES,
    PREFERENCE_STRENGTHS,
    SCOPE_KINDS,
    VERIFICATION_OUTCOMES,
)


_INCLUDE_DESCRIPTIONS: dict[AgentInclude, str] = {
    AgentInclude.CODING_PREFERENCES: "Policy / preference rules whose code_scope overlaps the task scope.",
    AgentInclude.INFRA_TOPOLOGY: "Service ↔ Deployment ↔ Environment ↔ DataStore neighbourhood.",
    AgentInclude.RECENT_CHANGES: "Recent change activities (PRs, commits) touching the scope.",
    AgentInclude.PRIOR_BUGS: "Known bug patterns whose symptom matches the query.",
    AgentInclude.PRIOR_FIXES: "Verified resolutions and attempted-failed fixes for the scope.",
    AgentInclude.DECISIONS: "ADR-style decisions affecting the scope.",
    AgentInclude.OWNERS: "Service / component owners derived from CODEOWNERS and equivalents.",
    AgentInclude.DOCS: "Project documentation references.",
    AgentInclude.SOURCE_STATUS: "Per-source ingestion freshness + coverage.",
    AgentInclude.SEMANTIC_SEARCH: "Free-form vector search across claim facts.",
}


def emit(stream: TextIO) -> None:
    print("# Agent Contract (generated)\n", file=stream)
    print(
        "_This file is generated by `scripts/generate_agent_contract.py`. "
        "Do not edit by hand; CI will fail on drift._\n",
        file=stream,
    )

    print("## Intents\n", file=stream)
    print("| Intent | Default Includes |", file=stream)
    print("|---|---|", file=stream)
    for intent in AgentIntent:
        includes = ", ".join(i.value for i in INTENT_INCLUDES.get(intent, ()))
        print(f"| `{intent.value}` | {includes} |", file=stream)
    print(file=stream)

    print("## Includes\n", file=stream)
    print("| Include | Description |", file=stream)
    print("|---|---|", file=stream)
    for include in AgentInclude:
        desc = _INCLUDE_DESCRIPTIONS.get(include, "(no description)")
        print(f"| `{include.value}` | {desc} |", file=stream)
    print(file=stream)

    print("## Record-type vocabularies\n", file=stream)
    print(
        "These enumerations validate the structured `context_record` payload "
        "(rebuild plan P6).\n",
        file=stream,
    )
    print("### Scope kinds\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(SCOPE_KINDS)), file=stream)
    print(file=stream)
    print("### Preference strengths\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(PREFERENCE_STRENGTHS)), file=stream)
    print(file=stream)
    print("### Preference audiences\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(PREFERENCE_AUDIENCES)), file=stream)
    print(file=stream)
    print("### Verification outcomes\n", file=stream)
    print(", ".join(f"`{v}`" for v in sorted(VERIFICATION_OUTCOMES)), file=stream)
    print(file=stream)


def main() -> int:
    emit(sys.stdout)
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
