"""Local daemon lifecycle port used by setup and host status surfaces."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from domain.lifecycle import SetupPlan, StepResult


class DaemonLifecyclePort(Protocol):
    home: Path
    in_process: bool

    def discovery(self) -> dict[str, str] | None: ...
    def status(self) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def logs(self, *, follow: bool = False) -> list[str]: ...
    def ensure(self, plan: SetupPlan | None = None) -> StepResult: ...
    def install(self) -> dict[str, Any]: ...
    def start(self, *, backend: str | None = None) -> dict[str, Any]: ...
    def stop(self) -> dict[str, Any]: ...
    def restart(self) -> dict[str, Any]: ...


__all__ = ["DaemonLifecyclePort"]

