from __future__ import annotations

from typing import overload

class FileSearchResultPy:
    @property
    def path(self) -> str: ...
    @property
    def score(self) -> int: ...

class ContentSearchResultPy:
    @property
    def path(self) -> str: ...
    @property
    def line(self) -> int: ...
    @property
    def snippet(self) -> str: ...
    @property
    def score(self) -> int: ...

class WorkspaceSearchIndex:
    def file_count(self) -> int: ...
    def content_file_count(self) -> int: ...
    def search_files(self, query: str, limit: int) -> list[FileSearchResultPy]: ...
    def search_content(self, query: str, limit: int) -> list[ContentSearchResultPy]: ...

class FileEntry:
    @property
    def path(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def object_id(self) -> str: ...

class GitRepositoryNotFoundError(Exception): ...
class GitRefNotFoundError(Exception): ...
class GitParseError(Exception): ...

def build_workspace_index(repo_dir: str) -> WorkspaceSearchIndex: ...
@overload
def bare_clone(
    repo_url: str,
    dest_path: str,
    git_ref: str,
    auth_token: str,
) -> None: ...
@overload
def bare_clone(
    repo_url: str,
    dest_path: str,
    git_ref: str,
    auth_token: None,
) -> None: ...
def list_files(repo_path: str, git_ref: str) -> list[FileEntry]: ...
