from enum import Enum


class SystemAgentType(Enum):
    QNA = "QNA_AGENT_CLASSIFIER"
    DEBUGGING = "DEBUGGING_AGENT_CLASSIFIER"
    UNIT_TEST = "UNIT_TEST_AGENT_CLASSIFIER"
    INTEGRATION_TEST = "INTEGRATION_TEST_AGENT_CLASSIFIER"
    CODE_CHANGES = "CODE_CHANGES_AGENT_CLASSIFIER"
    LLD = "LLD_AGENT_CLASSIFIER"


class AgentLLMType(Enum):
    CREWAI = "CREWAI"
    LANGCHAIN = "LANGCHAIN"


class AgentRuntimeLLMType(Enum):
    ANTHROPIC = "ANTHROPIC"
    OPENAI = "OPENAI"
