class FileUtils:
    EXCLUDE_EXTENSIONS = {
        "png",
        "jpg",
        "jpeg",
        "gif",
        "bmp",
        "tiff",
        "webp",
        "ico",
        "svg",
        "mp4",
        "avi",
        "mov",
        "wmv",
        "flv",
        "mkv",
        "webm",
        "mp3",
        "wav",
        "ogg",
        "m4a",
        "flac",
        "zip",
        "tar",
        "gz",
        "rar",
        "7z",
        "iso",
        "dmg",
        "exe",
        "dll",
        "so",
        "dylib",
        "bin",
        "pdf",
        "doc",
        "docx",
        "ppt",
        "pptx",
        "xls",
        "xlsx",
        "ipynb",
        "zlib",
        "pyc",
        "class",
        "o",
        "obj",
        "db",
        "sqlite",
        "sqlite3",
        "eot",
        "ttf",
        "woff",
        "woff2",
        "ds_store",
    }

    INCLUDE_EXTENSIONS = {
        "py",
        "pyi",
        "js",
        "jsx",
        "mjs",
        "cjs",
        "ts",
        "tsx",
        "c",
        "cc",
        "cpp",
        "cxx",
        "h",
        "hpp",
        "cs",
        "go",
        "java",
        "kt",
        "kts",
        "rb",
        "erb",
        "php",
        "rs",
        "swift",
        "scala",
        "groovy",
        "html",
        "htm",
        "css",
        "scss",
        "sass",
        "less",
        "json",
        "json5",
        "jsonc",
        "xml",
        "yaml",
        "yml",
        "toml",
        "ini",
        "cfg",
        "conf",
        "properties",
        "md",
        "markdown",
        "mdx",
        "sh",
        "bash",
        "zsh",
        "fish",
        "ps1",
        "psm1",
        "psd1",
        "bat",
        "cmd",
        "sql",
        "graphql",
        "gql",
        "vue",
        "svelte",
        "el",
        "ex",
        "exs",
        "elm",
        "ml",
        "mli",
        "ql",
        "proto",
        "txt",
        "xsq",
        "lua",
        "pl",
        "pm",
        "r",
        "dart",
        "sol",
        "rst",
        "adoc",
    }

    INCLUDE_FILENAMES = {
        "Dockerfile",
        "Makefile",
        "Jenkinsfile",
        "Vagrantfile",
        "Rakefile",
        "Gemfile",
        "Pipfile",
        "Procfile",
        ".gitignore",
        ".env",
        ".editorconfig",
        ".dockerignore",
        "docker-compose.yml",
        "docker-compose.yaml",
    }

    @staticmethod
    def is_valid_file_name(file_name: str) -> bool:
        if file_name in FileUtils.INCLUDE_FILENAMES:
            return True

        parts = file_name.split(".")
        ext = parts[-1].lower() if len(parts) > 1 else ""

        if ext in FileUtils.INCLUDE_EXTENSIONS:
            return True

        return False

    @staticmethod
    def is_excluded_file_name(file_name: str) -> bool:
        parts = file_name.split(".")
        ext = parts[-1].lower() if len(parts) > 1 else ""
        return ext in FileUtils.EXCLUDE_EXTENSIONS
